name: e2e-conditional
on:
  pull_request:
    types: [labeled]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: test
    if: github.event.label.name == 'run e2e extended test suite'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          wait-on: http://localhost:4200
    env:
      CYPRESS_authLogin: ${{ secrets.AUTHLOGIN }}
      CYPRESS_authPass: ${{ secrets.AUTHPASS }}
