name: gh-pages-publish
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Stage build artifacts
        run: |
          git add -f client/dist/
          git status
      - name: Make commit message
        run: |
          git config --global user.name "GitHub Actions"
          git commit -m "Deployed build artifacts (`date '+%F %T %Z'`)" || true
          git restore .
      - name: Push build artifacts to gh-pages branch
        run: git push origin HEAD:gh-pages --force
